# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video_download.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(597, 341)
        Form.setMinimumSize(QtCore.QSize(8, 0))
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(30, 70, 551, 141))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.loadFromFile_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.loadFromFile_btn.setObjectName("loadFromFile_btn")
        self.gridLayout_2.addWidget(self.loadFromFile_btn, 0, 2, 1, 1)
        self.addqueue_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.addqueue_btn.setObjectName("addqueue_btn")
        self.gridLayout_2.addWidget(self.addqueue_btn, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 1, 1, 1)
        self.download_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.download_btn.setObjectName("download_btn")
        self.gridLayout_2.addWidget(self.download_btn, 2, 2, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 1, 0, 2, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 230, 221, 21))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(30, 30, 541, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(30, 290, 181, 31))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "视频下载软件器 http://30daydo.com"))
        self.loadFromFile_btn.setText(_translate("Form", "文件导入"))
        self.addqueue_btn.setText(_translate("Form", "添加到队列"))
        self.download_btn.setText(_translate("Form", "下载"))
        self.label.setText(_translate("Form", "待下载URL"))
        self.pushButton.setText(_translate("Form", "支持视频下载网站一览"))
